apiVersion: v1
kind: Service
metadata:
  name: borrowing-service
spec:
  type: NodePort
  selector:
    app: borrowing-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30082
