---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: library-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: library-service
  template:
    metadata:
      labels:
        app: library-service
    spec:
      containers:
        - name: library-service
          image: library_service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: library-service
