apiVersion: v1
kind: Service
metadata:
  name: library-service
spec:
  type: NodePort
  selector:
    app: library-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30081
